version: '3.9'

services:

  #Backend service, servng api requests
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
    networks:
      - internal
    restart: always
    links: 
      - contracts
    depends_on: 
      - contracts

  #Frontend, relying on the backend for api calls
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    environment:
      - VUE_APP_BASE_URL=http://localhost/api/
    networks:
      - internal

  contracts:
    build:
      context: ./contracts
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
    expose: 
      - 8545
    networks:
      - internal
    #command: ["sleep 20", "&&", "npx", "truffle", "migrate", "--network", "development"]
    #command: ["sh","-c","sleep 15 && npx truffle migrate --network development"]
  #Reverse proxy routing the traffic to the right containers

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    environment:
      - HOST=localhost
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    networks:
      - internal

networks:
  internal:
    driver: bridge